[package]
name = "xbus"
version = "0.1.0"
authors = ["lolynx <londevil@gmail.com>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.7"
hyper = "0.12"
url = "1.7"
futures = "0.1"
tokio = "0.1"
tokio-io = "0.1"
log = "0.4"
http = "0.1"
percent-encoding = "1.0"
webpki = "0.18"
webpki-roots = "0.15"
tokio-rustls = "0.7"

[dependencies.rustls]
version = "0.13"
features = ["dangerous_configuration"]

[dev-dependencies]
env_logger = "0.4"
