[package]
name = "xbus"
version = "0.1.0"
authors = ["lolynx <londevil@gmail.com>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.7"
hyper = "0.11"
hyper-tls = "0.1"
native-tls = "0.1"
url = "1.4"
openssl = "0.9"
futures = "0.1"
tokio-core = "0.1"
